### ISSUE TITLE
Work on letterforms and harmonization

### ISSUE THREAD

**Issue by theseunbadejo** [theseunbadejo/nsibidi-libre#7]
Agyei mentioned I have to figure out how to harmonise the letterforms, for example the h, m, u and n have to be related and at the moment, the loop is getting in the way of that. 

I have to either figure out how to use the loop to achieve that or take the loop out and use it as a decoration after the skeleton has been properly designed.

Also, the slanted letterforms might make things a bit hard regarding spacing but I would resolve it.

**Comment by traviskochel** [comment]
Looking good! I like the more hand-drawn direction. Here are a few suggestions from the 1.0.4 proof.

- `m` stands out quite a bit in a line of text. A little thinning of the joins could help. I also wonder if extending the loop to the baseline will get a little more negative space inside its counter, which will help lighten it up.

- A few glyphs feel like they could use a little push in the hand-drawn direction that direction, as they feel more rigid than the new ones. `agvi`, and maybe the round strokes, like `bdoe` etc. Maybe you haven't gotten to these yet though.

- I wonder if the `u` needs the loop, to match the similar stroke in the `n`? 

- Maybe the bottom stroke of the `e` counter could be curved, so that it’s a continuous curve, rather than having the sharp corner. Like this: (forgive the crude sketch, I don’t have my iPad with me)
<img width="277" alt="Screen Shot 2023-11-20 at 3 16 44 PM" src="https://github.com/theseunbadejo/nsibidi-libre/assets/980360/8da45858-e514-4437-969f-aa490df5f9af">

**Comment by theseunbadejo** [comment]
Thanks a lot for this @traviskochel I had to divert from the handwritten direction last week as I had two directions to contemplate going in, the handwritten direction (which would take a lot more time considering spacing peculiarities that may arise) or the geometric direction (which is pretty much where I started from). I went back and decided to solve the main problems plaguing the skeleton, which is making sure the letterforms are related to one another. I was able to solve that with the direction I went in. I found subtle ways to embed Nsibidi visual language in the typeface skeleton (per your initial feedback) in the way my crossbars cut through the stems and in how curves are drawn as well. 

I added some more glyphs and worked on Upper case letters of my basic string, while also starting to figure out how I would want the Nsibidi radicals (as decorations) to work with the three other masters.

Here is an screenshot of what that looks like at the moment (I have Master 2 and Master 3 partly completed at the moment), you can also take a closer look at the changes in my glyphs file as well. 

<img width="771" alt="Screenshot 2023-11-27 at 5 44 29 PM" src="https://github.com/theseunbadejo/nsibidi-libre/assets/47482372/2e90e46e-6454-4a8d-9beb-00d869ca3351">
<img width="751" alt="Screenshot 2023-11-27 at 5 44 38 PM" src="https://github.com/theseunbadejo/nsibidi-libre/assets/47482372/07000ad2-9a88-4e77-8eb3-dd0a4aea4d8d">


I really appreciate your feedback so far and would love to hear what you think about this update.

**Comment by traviskochel** [comment]
Hi Seun,

Using the proof you sent over email today, here are a few suggestions. If you have trouble reading anything let me know. And we can talk in more detail in tomorrow's meeting.
![Screen Shot 2023-11-29 at 2 38 41 PM](https://github.com/theseunbadejo/nsibidi-libre/assets/980360/1f2eed9d-d377-4788-bec2-b95d6686c72f)
![Screen Shot 2023-11-29 at 2 41 43 PM](https://github.com/theseunbadejo/nsibidi-libre/assets/980360/6a36be19-5718-43eb-a220-9989ac8aa0ee)

**Comment by n8willis** [comment]
I concur about the widths of cap C and G; try to make them a bit closer to the width seen in cap D: those are all related shapes. Try to make C and G in between where they are now and the width of D (not counting the sidebearings on any of these...).

**Comment by n8willis** [comment]
On some of the forms where Travis has indicated some bumpiness, I think you can smoother that out by evening-up some of your control points.

Using the cap E as an example, in the top curve, see how the control points I've marked are not the same distance-away-from (or distance above, so to speak) the contour itself. For two control points that face each other like that, that's where you see un-smoothness, because the contour is a transition line between them.

Similarly, the two facing control point "arms" (which is probably not the official term) are different lengths. That also makes the contour less smooth.

So, compare those facing control points in the top to the facing control points down at the bottom: the bottom two are equalized, and the contour is smoother.

I also noticed, in this view, that there are some corner points in the curved portion of the bottom of the E, as well as a couple of places where there are two points almost right next to each other. That can also introduce unwanted bumpiness. When they're so close together, they're safe to remove.

<img width="464" alt="Screen Shot 2023-11-30 at 11 52 00 AM" src="https://github.com/theseunbadejo/nsibidi-libre/assets/2192132/aa283417-6bf3-4f7d-a448-66cb70eba578">

I think it is worth making a pass through the letterforms where you just focus on regularizing things like that, without tackling other design questions. If you do it all at the same time like that, you'll have an easier time looking at other considerations.

**Comment by traviskochel** [comment]
In that example, regarding the bumpiness, I think just removing some of the points will help quite a bit. Each point along a smooth curve is an opportunity for a bump to appear. So unless a point is defining an extreme, corner, or change in curve speed/direction, it's worth questioning if you really need it. Here are a few I think you could get rid of:

<img width="464" alt="286924909-aa283417-6bf3-4f7d-a448-66cb70eba578" src="https://github.com/theseunbadejo/nsibidi-libre/assets/980360/709a7360-dca3-40b7-93b6-485e1d0f67f6">

**Comment by theseunbadejo** [comment]
Thanks a lot for the feedback so far, I made updates to this and worked on a few more glyphs, You can check the brief [here](https://github.com/theseunbadejo/nsibidi-libre/blob/main/documentation/Nsibidi%20Libre_Font%20Proof_%202023-12-13%20at%2001.18.18.pdf). I would appreciate some feedback, thanks!
